version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - cs_pg_data:/var/lib/postgresql/data
  server:
    build:
      context: backend
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    volumes:
      - webpack_output:/concertspot/server/build
      - ./backend:/concertspot
  client:
    build:
      context: client
    volumes:
      - webpack_output:/concertspot/build
      - ./client/src:/concertspot/src
      - ./client/test:/concertspot/test
  setup-db:
    build:
      context: scripts
    depends_on:
      - db
volumes:
  cs_pg_data:
  webpack_output:
